spring.application.name=travel-planner

spring.datasource.url=jdbc:postgresql://localhost:5435/travel_planner
spring.datasource.username=postgres
spring.datasource.password=Diana

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

google.api-key=${GOOGLE_API_KEY}

duffel.api.token=${DUFFEL_API_TOKEN}

hotelbeds.api-key=${HOTELBEDS_API_KEY}
hotelbeds.secret=${HOTELBEDS_SECRET}

unsplash.api-key: ${UNSPLASH_API_KEY}